var cn = ["average fixed cost (AFC)",
"average product (AP)",
"average revenue",
"average total cost (ATC)",
"average variable cost (AVC",
"break-even output",
"break-even point",
"budget constraint",
"budget line",
"business firm", 
"businesses",
"capital goods",
"capital ",
"capital-intensive goods",
"capital-saving technology",
"capital-using technology",
"cardinal utility",
"ceiling price",
"Coase theorem",
"competition",
"complementary goods", 
"constant returns to scale",
"constant-cost industry",
"consumer equilibrium",
"consumer goods",
"consumer surplus",
"cross elasticity of demand",
"deadweight loss",
"decreasing-cost industry",
"derived demand",
"diminishing marginal returns",
"diseconomies of scale",
"economic rent ",
"economies of scale",
"elastic demand",
"elastic supply ",
"elasticity coefficient",
"elasticity formula",
"elasticity of resource demand",
"entrepreneurial ability",
"equilibrium position",
"equilibrium price",
"equilibrium quantity",
"expectations",
"fixed resource",
"homogeneous oligopoly",
"human capital",
"imperfect competition",
"incentive function",
"income effect ",
"income elasticity of demand",
"income inequality ",
"increasing marginal returns",
"increasing returns",
"increasing-cost industry",
"independent goods",
"indifference curve",
"indifference map ",
"inelastic demand",
"inelastic supply",
"inferior good",
"intertemporal choice",
"kinked-demand curve",
"labor-intensive good",
"land-intensive goods",
"law of diminishing marginal utility",
"least-cost combination of resources",
"long run",
"long-run competitive equilibrium",
"long-run supply curve",
"long-run supply",
"marginal analysis",
"marginal benefit",
"marginal cost",
"marginal cost-marginal benefit rule",
"marginal product",
"marginal productivity theory of income distribution",
"marginal rate of substitution",
"marginal resource cost",
"marginal revenue product",
"marginal revenue productivity",
"marginal revenue",
"marginal utility",
"marginal-revenue-marginal-cost approach",
"microeconomics",
"macroeconomics",
"midpoint formula ",
"minimum efficient scale",
"monopolistic competition",
"monopoly",
"monopsony", 
"MR = MC",
"MRP = MRC",
"natural monopoly",
"nonprice competition",
"normal good",
"oligopoly",
"opportunity-cost ratio",
"ordinal utility",
"output effect",
"P = MC rule",
"perfectly elastic demand",
"perfectly elastic supply",
"perfectly inelastic demand",
"perfectly inelastic supply",
"per-unit production cost ",
"price ceiling",
"price discrimination",
"price elasticity of demand",
"price elasticity of supply",
"price floor",
"price leadership",
"price maker",
"price support", 
"price taker",
"producer surplus",
"product differentiation",
"product market",
"profit",
"profit-maximizing combination of resources",
"purchasing power",
"pure competition",
"pure monopoly",
"pure profit",
"short run ",
"short-run competitive equilibrium",
"short-run supply curve",
"shutdown case",
"standardized product",
"substitute goods",
"substitute resources",
"substitution effect ",
"sunk cost",
"time preference",
"total cost",
"total demand",
"total product (TP)",
"total revenue (TR)",
"total supply",
"total utility",
"total-revenue test",
"unit elasticity",
"unit labor cost",
"unlimited wants",
"utility",
"utility-maximizing rule",
"value judgment",
"variable cost ",
"very long run",
"X-inefficiency",
"allocative efficiency",
"barrier to entry",
"barter",
"ceteris paribus assumption",
"change in demand",
"change in quantity demanded",
"change in quantity supplied",
"change in supply",
"circular flow diagram",
"comparative advantage",
"constant opportunity cost",
"demand ",
"demand curve", 
"demand schedule",
"demand shocks",
"determinants of demand",
"determinants of supply",
"diminishing marginal utility",
"division of labor",
"economic cost",
"economic efficiency",
"economic model ",
"economic perspective", 
"economic profit ",
"economic resources",
"economics",
"efficiency",
"efficient allocation of resource",
"equality-efficiency trade-off",
"explicit cost",
"factors of production",
"fallacy of composition",
"final goods",
"firm",
"fixed cost",
"gains from trade",
"households",
"implicit cost ",
"increase in demand",
"increase in supply",
"Individual demand",
"individual supply",
"intermediate goods",
"invisible hand",
"labor ",
"land ",
"law of demand",
"law of diminishing returns",
"law of increasing opportunity costs",
"law of supply",
"market",
"market demand",
"market economy",
"market system",
"normal profit",
"normative economics",
"opportunity cost",
"other-things-equal assumption",
"positive economics",
"post hoc, ergo propter hoc fallacy",
"price",
"principle of comparative advantage",
"production possibilities curve",
"productive efficiency",
"productivity",
"quantity demanded",
"quantity supplied",
"rational behavior",
"rationing function of prices",
"resource",
"resource market", 
"scarce resources ",
"service ",
"shocks",
"shortage", 
"specialization",
"supply ",
"supply curve",
"supply schedule", 
"supply shocks",
"surplus ",
"technology",
"trade-off",
"tragedy of the commons",
"accounting profit "];