var def = ["A firm's total fixed cost divided by output (the quantity of product produced).",
"The total output produced per unit of a resource employed ( total product divided by the quantity of that employed resource).",
"Total revenue from the sale of a product divided by the quantity of the product sold (demanded); equal to the price at which the product is sold when all units of the product are sold at the same price.",
"A firm's total cost divided by output (the quantity of product produced); equal to average fixed cost plus average variable cost .",
"A firm's total variable cost divided by output (the quantity of product produced).",
"Any output at which a (competitive) firm's total cost and total revenue are equal; an output at which a firm has neither an economic profit nor an economic loss, at which it earns only a normal profit.",
"An output at which a firm makes a normal profit ( total revenue 5 total cost ) but not an economic profit .",
"The limit that the size of a consumer's income (and the prices that must be paid for goods and services) imposes on the ability of that consumer to obtain goods and services.",
"A line that shows the different combinations of two products a consumer can purchase with a specific money income,given the products' prices.",
"Economic entities (firms) that purchase (demands) resources and provides (supplies) goods and services to the market.",
"Economic entities (firms) that purchase resources and provide goods and services to the economy.",
"Human-made resources (buildings, machinery, and equipment) used to produce goods and services; goods that do not directly satisfy human wants; also called capital goods.",
"Human-made resources (buildings, machinery, and equipment) used to produce goods and services; goods that do not directly satisfy human wants; also called capital goods.",
"Products that require relatively large amounts of capital to produce.",
"An improvement in technology that permits a greater quantity of a product to be produced with a specific amount of capital (or permits the same amount of the product to be produced with a smaller amount of capital).",
"An improvement in technology that requires the use of a greater amount of capital to produce a specific quantity of a product.",
"Satisfaction ( utility ) that can be measured via cardinal numbers (1, 2, 3…), with all the mathematical properties of those numbers such as addition, subtraction, multiplication, and division being applicable.",
"A legally established maximum price for a good or service.",
"The idea, first stated by economist Ronald Coase, that some externalities can be resolved through private negotiations of the affected parties.",
"The presence in a market of independent buyers and sellers competing with one another along with the freedom of buyers and sellers to enter and leave the market.",
"Products and services that are used together. When the price of one falls, the demand for the other increases (and conversely).",
"Unchanging average total cost of producing a product as the firm expands the size of its plant (its output) in the long run .",
"An industry in which expansion by the entry of new firms has no effect on the prices firms in the industry must pay for resources and thus no effect on production costs.",
"In marginal utility theory, the combination of goods purchased based on marginal utility (MU) and price (P) that maximizes total utility ; the combination for goods X and Y at which MU x yP x 5 MU y yP y . In indifference curve analysis, the combination of goods purchased that maximize total",
"Products and services that satisfy human wants directly.",
"The difference between the maximum price a consumer is (or consumers are) willing to pay for an additional unit of a product and its market price; the triangular area below the demand curve and above the market price. ",
"The ratio of the percentage change in quantity demanded of one good to the percentage change in the price of some other good. A positive coefficient indicates the two products are substitute goods; a negative coefficient indicates they are complementary goods .",
"A loss in surplus value (consumer surplus, producer surplus) due to distortions in the market -- distortions that drive a wedge between the marginal costs of production and the marginal benefit of consumption or price. ",
"An industry in which expansion through the entry of firms lowers the prices that firms in the ",
"The demand for a resource that depends on the demand for the products it helps to produce.",
"The principle that as successive increments of a variable resource are added to a fixed resource, the marginal product of the variable resource will eventually decrease.",
"Increases in the average total cost of producing a product as the firm expands the size of its plant (its output) in the long run .",
"The price paid for the use of land and other natural resources, the supply of which is fixed (perfectly inelastic) .",
"Reductions in the average total cost of producing a product as the firm expands the size of plant (its output) in the long run; the economies of mass production.",
"Product or resource demand whose price elasticity is greater than 1. This means the resulting change in quantity demanded is greater than the percentage change in price .",
"Product or resource supply whose price elasticity is greater than 1. This means the resulting change in quantity supplied is greater than the percentage change in price.",
"The number obtained when the percentage change in quantity demanded (or supplied) is divided by the percentage change in the price of the commodity.",
"The ratio of the percentage change in quantity demanded of a product or resource to the percentage change in its price; a measure of the responsiveness of buyers to a change in the price of a product or resource.",
"A measure of the responsiveness of firms to a change in the price of a particular resource they employ or use; the percentage change in the quantity of the resource demanded divided by the percentage change in its price.",
"The human resource that combines the other resources to produce a product, makes nonroutine decisions, innovates, and bears risks.",
"In the indifference curve model, the combination of two goods at which a consumer maximizes his or her utility (reaches the highest attainable indifference curve ), given a limited amount to spend (a budget constraint ).",
"The price in a competitive market at which the quantity demanded and the quantity supplied are equal, there is neither a shortage nor a surplus, and there is no tendency for",
"The quantity at which the intentions of buyers and sellers in a particular market match at a particular price such that the quantity demanded and the quantity supplied are",
"The anticipations of consumers, firms, and others about future economic conditions.",
"Any resource whose quantity cannot be changed by a firm in the short run .",
"An oligopoly in which the firms produce a standardized product .",
"The knowledge and skills that make a person productive.",
"All market structures except pure competition; includes monopoly, monopolistic competition, and oligopoly .",
"The inducement that an increase in the price of a commodity gives to sellers to make more of it available (and conversely for a decrease in price), and the inducement that an increase in price offers to buyers to purchase smaller quantities (and conversely for a decrease in price).",
"A change in the quantity demanded of a product that results from the change in real income (purchasing power) caused by a change in the product's price.",
"The ratio of the percentage change in the quantity demanded of a good to a percentage change in consumer income; measures the responsiveness of consumer purchases to income changes.",
"The unequal distribution of an economy's total income among households or families.",
"An increase in the marginal product of a resource as successive units of the resource are employed.",
"An increase in a firm's output by a larger percentage than the percentage increase in its inputs.",
"An industry in which expansion through the entry of new firms raises the prices firms in the Unused funds accumulate from year to year and later can be used to supplement Medicare .",
"Products or services for which there is little or no relationship between the price of one and the demand for the other. When the price of one rises or falls, the demand for the other tends to remain constant.",
"A curve showing the different combinations of two products that yield the same satisfaction or utility to a consumer.",
"A set of indifference curves, each representing a different level of utility, that together show the preferences of a consumer.",
"Product or resource demand for which the elasticity coefficient for price is less than 1. This means the resulting percentage change in quantity demanded is less than the percentage change in price .",
"Product or resource supply for which the price elasticity coefficient is less than 1. The percentage change in quantity supplied is less than the percentage change in price .",
"A good or service whose consumption declines as income rises, prices held constant.",
"Choices between benefits obtainable in one time period and benefits achievable in a later time period; comparisons that individuals and society must make between the reductions in current consumption that are necessary to fund current investments and the higher levels of future consumption",
"The demand curve for a noncollusive oligopolist, which is based on the assumption that rivals will match a price decrease and will ignore a price increase.",
"Products requiring relatively large amounts of labor to produce.",
"Products requiring relatively large amounts of land to produce.",
"The principle that as a consumer increases the consumption of a good or service, the marginal utility obtained from each additional unit of the good or service decreases.",
"The quantity of each resource a firm must employ in order to produce a particular output at the lowest total cost; the combination at which the ratio of the ???",
"In microeconomics, a period of time long enough to enable producers of a product to change the quantities of all the resources they employ; period in which all resources and costs are variable and no resources or costs are fixed. (2) In macroeconomics, a period sufficiently long for nominal wages and",
"The price at which firms in pure competition neither obtain economic profit nor suffer economic losses in the long run and in which the total quantity demanded and supplied are equal; a price equal to the marginal cost and the minimum long-run average total cost of producing the product.",
"As it applies to macroeconomics, a supply curve for which price, but not real output, changes when the demand curves shifts; a vertical supply curve that implies fully flexible prices.",
"In microeconomics, a schedule or curve showing the prices at which a purely competitive industry will make various quantities of the product available in the long run .",
"The comparison of marginal (extra or additional) benefits and marginal costs, usually for decision making.",
"The extra (additional) benefit of consuming 1 more unit of some good or service; the change in total benefit when 1 more unit is consumed.",
"The extra (additional) cost of producing 1 more unit of output; equal to the change in total cost divided by the change in output (and, in the short run, to the change in total variable cost divided by the change in output).",
"As it applies to cost benefit analysis , the tenet that a government project or program should be expanded to the point where the marginal cost and marginal benefit of additional expenditures are equal.",
"The additional output produced when 1 additional unit of a resource is employed (the quantity of all other resources employed remaining constant); equal to the change in total product divided by the change in the quantity of a resource employed.",
"The contention that the distribution of income is equitable when each unit of each resource receives a money payment equal to its marginal contribution to the firm's revenue (its marginal revenue product ).",
"The rate at which a consumer is willing to substitute one good for another (from a given combination of goods) and remain equally satisfied (have the same total utility ); equal to the slope of a consumer's indifference curve at each point on the curve.",
"The amount the total cost of employing a resource increases when a firm employs 1 additional unit of the resource (the quantity of all other resources employed remaining constant); equal to the change in the total cost of the resource divided by the change in the quantity of the resource employed.",
"The change in a firm's total revenue when it employs 1 additional unit of a resource (the quantity of all other resources employed remaining constant); equal to the change in total revenue divided by the change in the quantity of the resource employed.",
"The change in a firm's total revenue when it employs 1 additional unit of a resource (the quantity of all other resources employed remaining constant); equal to the change in total revenue divided by the change in the quantity of the resource employed.",
"The change in total revenue that results from the sale of 1 additional unit of a firm's product; equal to the change in total revenue divided by the change in the quantity of the product sold.",
"The extra utility a consumer obtains from the consumption of 1 additional unit of a good or service; equal to the change in total utility divided by the change in the quantity consumed.",
"A method of determining the total output where economic profit is a maximum (or losses are a minimum) by comparing the marginal revenue and the marginal cost of each additional unit of output.",
"The part of economics concerned with decision making by individual units such as a household , a firm , or an industry and with individual markets, specific goods and services, and product and resource prices.",
"The branch of economics concerned with the aggregate behavior of households, business firms, government, and the international sector. Addresses issues of stable economic growth, inflation and deflation, employment and unemployment, interest rates and exchange rates. Guides in policies to address these issues.", 
"A method for calculating price elasticity of demand or price elasticity of supply that averages the two prices and two quantities as the reference points for computing percentages.",
"The lowest level of output at which a firm can minimize long-run average total cost .",
"A market structure in which many firms sell a differentiated product, into which entry is relatively easy, in which the firm has some control over its product price, and in which there is considerable nonprice competition .",
"A market structure in which there is only a single seller of a good, service, or resource. In antitrust law, a dominant firm that accounts for a very high percentage of total sales within a particular market.",
"A market structure in which there is only a single buyer of a good, service, or resource.",
"The principle that a firm will maximize its profit (or minimize its losses) by producing the output at which marginal revenue and marginal cost are equal, provided product price is equal to or greater than average variable cost .",
"The principle that to maximize profit (or minimize losses), a firm should employ the quantity of a resource",
"An industry in which economies of scale are so great that a single firm can produce the product at a lower average total cost than would be possible if more than one firm produced the product.",
"Competition based on distinguishing one's product by means of product differentiation and then advertising the distinguished product to consumers.",
"A good or service whose consumption increases when income increases and falls when income decreases, price remaining constant.",
"A market structure in which a few firms sell either a standardized or differentiated product, into which entry is difficult, in which the firm has limited control over product price because of mutual interdependence (except when there is collusion among firms), and in which there is typically nonprice",
"An equivalency showing the number of units of two products that can be produced with the same resources; the cost 1 corn ; 3 olives shows that the resources required",
"Satisfaction that is measured by having consumers compare and rank products (or combinations of products) as to preference, without asking them to specify the absolute amounts of satisfaction provided by the products.",
"The situation in which an increase in the price of one input will increase a firm's production costs and reduce its level of output, thus reducing the demand for other inputs; conversely for a decrease in the price of the input.",
"The principle that a purely competitive firm will maximize its profit or minimize its loss by producing that output at which the price of the product is equal to marginal cost, provided that price is equal to or greater than average variable cost in the short run and equal to or greater than average total cost in the long run.",
"Product or resource demand in which quantity demanded can be of any amount at a particular product price; graphs as a horizontal demand curve .",
"Product or resource supply in which quantity supplied can be of any amount at a particular product or resource price; graphs as a horizontal supply curve .",
"Product or resource demand in which price can be of any amount at a particular quantity of the product or resource demanded; quantity demanded does not respond to a change in price; graphs as a vertical demand curve .",
"Product or resource supply in which price can be of any amount at a particular quantity of the product or resource demanded; quantity supplied does not respond to a change in price; graphs as a vertical supply curve .",
"The average production cost of a particular level of output; total input cost divided by units of output.",
"A legally established maximum price for a good or service.",
"The selling of a product to different buyers at different prices when the price differences are not justified by differences in cost.",
"The ratio of the percentage change in quantity demanded of a product or resource to the percentage change in its price; a measure of the responsiveness of buyers to a change in the price of a product or resource.",
"The ratio of the percentage change in quantity supplied of a product or resource to the percentage change in its price; a measure of the responsiveness of producers to a change in the price of a product or resource.",
"A legally determined minimum price above the equilibrium price .",
"An informal method that firms in an oligopoly may employ to set the price of their product: One firm (the leader) is the first to announce a change in price, and the other firms (the followers) soon announce identical or similar changes.",
"A seller (or buyer) that is able to affect the product or resource price by changing the amount it sells (or buys).",
"A minimum price that government allows sellers to receive for a good or service; a legally established or maintained minimum price.",
"A seller (or buyer) that is unable to affect the price at which a product or resource sells by changing the amount it sells (or buys).",
"The difference between the actual price a producer receives (or producers receive) and the minimum acceptable price; the triangular area above the supply curve and below",
"A strategy in which one firm's product is distinguished from competing products by means of its design, related services, quality, location, or other attributes (except price).",
"A market in which products are sold by firms and bought by households .",
"The return to the resource entrepreneurial ability (see normal profit ); total revenue minus total cost (see economic profit ).",
"The quantity of each resource a firm must employ to maximize its profit or minimize its loss; the combination in which the marginal revenue product of each resource is equal to its marginal resource cost (to its price if the resource is employed in a competitive market).",
"The amount of goods and services that a monetary unit of income can buy.",
"A market structure in which a very large number of firms sells a standardized product, into which entry is very easy, in which the individual seller has no control over the",
"A market structure in which one firm sells a unique product, into which entry is blocked, in which the single firm has considerable control over product price, and in which nonprice competition may or may not be found.",
"The total revenue of a firm less its economic costs (which include both explicit costs and implicit costs ); also called pure profit and above-normal profit.",
"In microeconomics, a period of time in which producers are able to change the quantities of some but not all of the resources they employ; a period in which some resources (usually plant) are fixed and some are variable. (2) In macroeconomics, a period in which nominal wages and other input prices do not change in response to a change in the price level.",
"The price at which the total quantity of a product supplied in the short run in a purely competitive industry equals the total quantity of the product demanded and that is equal to or greater than average variable cost .",
"A supply curve that shows the quantity of a product a firm in a purely competitive industry will offer to sell at various prices in the short run; the portion of the firm's short-run marginal cost curve that lies above its average-variable-cost curve.",
"The circumstance in which a firm would experience a loss greater than its total fixed cost if it were to produce any output greater than zero; alternatively, a situation in which a firm would cease to operate when the price at which it can sell its product is less than its average variable cost .",
"A product whose buyers are indifferent to the seller from whom they purchase it as long as the price charged by all sellers is the same; a product all units of which are identical and thus are perfect substitutes for each other.",
"Products or services that can be used in place of each other. When the price of one falls, the demand for the other product falls; conversely, when the price of one product rises, the demand for the other product rises.",
"Productive inputs that can be used instead of other inputs in the production process; resources for which an increase in the price of one leads to an increase in the demand for the other.",
"A change in the quantity demanded of a consumer good that results from a change in its relative expensiveness caused by a change in the product's price; (2) the effect of a change in the price of a resource on the quantity of the resource employed by a firm, assuming no change in its output.",
"A cost that has been incurred and cannot be recovered.",
"The human tendency for people, because of impatience, to prefer to spend and consume in the present rather than save and wait to spend and consume in the future; this inclination varies in strength among individuals",
"The sum of fixed cost and variable cost .",
"The demand schedule or the demand curve of all buyers of a good or service; also called market demand.",
"The total output of a particular good or service produced by a firm (or a group of firms or the entire economy).",
"The total number of dollars received by a firm (or firms) from the sale of a product; equal to the total expenditures for the product produced by the firm (or firms); equal to the quantity sold (demanded) multiplied by the price at which it is sold.",
"The supply schedule or the supply curve of all sellers of a good or service; also called market supply.",
"The total amount of satisfaction derived from the consumption of a single product or a combination of products.",
"A test to determine elasticity of demand between any two prices: Demand is elastic if total revenue moves in the opposite direction from price; it is inelastic when it moves in the same direction as price; and it is of unitary elasticity when it does not change when price changes.",
"Demand or supply for which the elasticity coefficient is equal to 1; means that the percentage change in the quantity demanded or supplied is equal to the percentage change in price.",
"Labor cost per unit of output; total labor cost divided by total output; also equal to the nominal wage rate divided by the average product of labor.",
"The insatiable desire of consumers for goods and services that will give them satisfaction or utility .",
"The want-satisfying power of a good or service; the satisfaction or pleasure a consumer obtains from the consumption of a good or service (or from the consumption of a collection of goods and services).",
"The principle that to obtain the greatest utility, a consumer should allocate money income so that the last dollar spent on each good or service yields the same marginal utility.",
"Opinion of what is desirable or undesirable; belief regarding what ought or ought not to be in terms of what is right (or just) or wrong (or unjust).",
"A cost that in total increases when the firm increases its output and decreases when the firm reduces its output.",
"A period long enough that technology can change and firms can introduce new products.",
"The production of output, whatever its level, at a higher average (and total) cost than is necessary for producing that level of output.",
"The apportionment of resources among firms and industries to obtain the production of the products most wanted by society (consumers); the output of each product at which its marginal cost and price or marginal benefit are equal, and at which the sum of consumer surplus and producer surplus is maximized.",
"Anything that artificially prevents the entry of firms into an industry.",
"The exchange of one good or service for another good or service.",
"The assumption that factors other than those being considered are held constant; ceteris paribus assumption.",
"A movement of an entire demand curve or schedule such that the quantity demanded changes at every particular price; caused by a change in one or more of the determinants",
"A change in the quantity demanded along a fixed demand curve (or within a fixed demand schedule) as a result of a change in the price of the product.",
"A change in the quantity supplied along a fixed supply curve (or within a fixed supply schedule) as a result of a change in the product's price.",
"A movement of an entire supply curve or schedule such that the quantity supplied changes at every particular price; caused by a change in one or more of the determinants of supply .",
"An illustration showing the flow of resources from households to firms and of products from firms to households. These flows are accompanied by reverse flows of money from firms to households and from households to firms.",
"A situation in which a person or country can produce a specific product at a lower opportunity cost than some other person or country; the basis for specialization and trade.",
"An opportunity cost that remains the same for each additional unit as a consumer (or society) shifts purchases (production) from one product to another along a straight-line budget line ( production possibilities curve ).",
"A schedule showing the amounts of a good or service that buyers (or a buyer) wish to purchase at various prices during some time period.",
"A curve illustrating demand.",
"A schedule showing the amounts of a good or service that buyers (or a buyer) wish to purchase at various prices during some time period.",
"Sudden, unexpected changes in demand.",
"Factors other than price that determine the quantities demanded of a good or service.",
"Factors other than price that determine the quantities supplied of a good or service.",
"The principle that as a consumer increases the consumption of a good or service, the marginal utility obtained from each additional unit of the good or service decreases.",
"The separation of the work required to produce a product into a number of different tasks that are performed by different workers; specialization of workers.",
"A payment that must be made to obtain and retain the services of a resource; the income a firm must provide to a resource supplier to attract the resource away from an alternative use; equal to the quantity of other products that cannot be produced when resources are instead used to make a particular product.",
"The use of the minimum necessary resources to obtain the socially optimal amounts of goods and services; entails both productive efficiency and allocative efficiency .",
"A simplified picture of economic reality; an abstract generalization.",
"A viewpoint that envisions individuals and institutions making rational decisions by comparing the marginal benefits and marginal costs associated with their actions.",
"The total revenue of a firm less its economic costs (which include both explicit costs and implicit costs ); also called pure profit and above-normal profit.",
"The land, labor, capital, and entrepreneurial ability that are used in the production of goods and services; productive agents; factors of production.",
"The social science concerned with how individuals, institutions, and society make optimal (best) choices under conditions of scarcity.",
"An allocation of resources that results in a state where the marginal cost of production is exactly equal to the marginal benefits of consumption.",
"That allocation of an economy's resources among the production of different products that leads to the maximum satisfaction of consumers' wants, thus producing the socially optimal mix of output with society's scarce resources.",
"The decrease in economic efficiency that may accompany a decrease in income inequality; the presumption that some income inequality is required to achieve economic efficiency.",
"The monetary payment a firm must make to an outsider to obtain a resource .",
"Economic resources: land, capital, labor, and entrepreneurial ability .",
"The false notion that what is true for the individual (or part) is necessarily true for the group (or whole).",
"Goods that have been purchased for final use and not for resale or further processing or manufacturing.",
"An organization that employs resources to produce a good or service for profit and owns and operates one or more plants .",
"Any cost that in total does not change when the firm changes its output; the cost of fixed resources .",
"The extra output that trading partners obtain through specialization of production and exchange of goods and services.",
"Economic entities (of one or more persons occupying a housing unit) that provide resources to the economy and use the income received to purchase goods and services that satisfy economic wants.",
"The monetary income a firm sacrifices when it uses a resource it owns rather than supplying the resource in the market; equal to what the resource could have earned in the next best use.",
"An increase in the quantity demanded of a good or service at every price; a shift of the demand curve to the right.",
"An increase in the quantity supplied of a good or service at every price; a shift of the supply curve to the right.",
"The demand schedule or demand curve of a single buyer.",
"The supply schedule or supply curve of a single seller.",
"Products that are purchased for resale or further processing or manufacturing.",
"The tendency of firms and resource suppliers that seek to further their own self-interests in competitive markets to also promote the interests of society.",
"People's physical and mental talents and efforts that are used to help produce goods and services.",
"Natural resources (free gifts of nature) used to produce goods and services.",
"The principle that, other things equal, an increase in a product's price will reduce the quantity of it demanded, and conversely for a decrease in price.",
"The principle that as successive increments of a variable resource are added to a fixed resource, the marginal product of the variable resource will eventually decrease.",
"The principle that as the production of a good increases, the opportunity cost of producing an additional unit rises.",
"The principle that, other things equal, an increase in the price of a product will increase the quantity of it supplied, and conversely for a price decrease.",
"Any institution or mechanism that brings together buyers (demanders) and sellers (suppliers) of a particular good or service.",
"The demand schedule or the demand curve of all buyers of a good or service; also called market demand.",
"An economy in which the private decisions of consumers, resource suppliers, and firms determine how resources are allocated; the market system .",
"All the product and resource markets of a market economy and the relationships among them; a method that allows the prices determined in those markets to allocate the economy's scarce resources and to communicate and coordinate the decisions made by consumers, firms, and resource suppliers.",
"The payment made by a firm to obtain and retain entrepreneurial ability; the minimum income entrepreneurial ability must receive to induce it to perform entrepreneurial functions for a firm.",
"The part of economics involving value judgments about what the economy should be like; focused on which economic goals and policies should be implemented; policy economics.",
"The amount of other products that must be forgone or sacrificed to produce a unit of a product.",
"The assumption that factors other than those being considered are held constant; ceteris paribus assumption.",
"The analysis of facts or data to establish scientific generalizations about economic behavior.",
"The false belief that when one event precedes another, the first event must have caused the second event.",
"The amount of money needed to buy a particular good, service, or resource.",
"The proposition that an individual, region, or nation will benefit if it specializes in producing goods for which its own opportunity costs are lower than the opportunity costs of a trading partner, and then exchanging some of the products in which it specializes for other desired goods.",
"A curve showing the different combinations of two goods or services that can be produced in a full-employment, full-production economy where the available supplies of resources and technology are fixed.",
"The production of a good in the least costly way; occurs when production takes place at the output at which average total cost is a minimum and marginal product per dollar's worth of input is the same for all inputs.",
"A measure of average output or real output per unit of input. For example, the productivity of labor is determined by dividing real output by hours of work.",
"The amount of a good or service that buyers (or a buyer) are willing and able to purchase at a specific price during a specified period of time.",
"The amount of a good or service that producers (or a producer) are willing and able to make available for sale at a specific price during a specified period of time.",
"Human behavior based on comparison of marginal costs and marginal benefits; behavior designed to maximize total utility.",
"The ability of market forces in competitive markets to equalize quantity demanded and quantity supplied and to eliminate shortages and surpluses via changes in prices.",
"A natural, human, or manufactured item that helps produce goods and services; a productive agent or factor of production.",
"A market in which households sell and firms buy resources or the services of resources.",
"The limited quantities of land, capital, labor, and entrepreneurial ability that are never sufficient to satisfy people's virtually unlimited economic wants.",
"An (intangible) act or use for which a consumer, firm, or government is willing to pay.",
"Sudden, unexpected changes in demand (or aggregate demand ) or supply (or aggregate supply).",
"The amount by which the quantity demanded of a product exceeds the quantity supplied at a particular (below equilibrium) price.",
"The use of the resources of an individual, a firm, a region, or a nation to concentrate production on one or a small number of goods and services.",
"A schedule showing the amounts of a good or service that sellers (or a seller) will offer at various prices during some period.",
"A curve illustrating supply .",
"A schedule showing the amounts of a good or service that sellers (or a seller) will offer at various prices during some period.",
"Sudden, unexpected changes in aggregate supply.",
"The amount by which the quantity supplied of a product exceeds the quantity demanded at a specific (above-equilibrium) price.",
"The body of knowledge and techniques that can be used to combine economic resources to produce goods and services.",
"The sacrifice of some or all of one economic goal, good, or service to achieve some other goal, good, or service.",
"The tendency for commonly owned natural resources to be overused, neglected, or degraded because their common ownership gives nobody an incentive to maintain",
"The total revenue of a firm less its explicit costs; the profit (or net income) that appears on accounting statements and that is reported to the government for tax purposes."];
